# Generated by Django 5.2.4 on 2025-10-12 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mavtournaments', '0002_teammembership_team_players'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['round__index', 'slot'], 'permissions': [('advance_match', 'Can advance winners in matches')]},
        ),
        migrations.AlterModelOptions(
            name='tournament',
            options={'permissions': [('manage_seeding', 'Can generate/seed brackets'), ('manage_teams', 'Can add/edit teams in tournament')]},
        ),
    ]
