# Generated by Django 5.2.4 on 2025-10-13 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mavtournaments', '0003_alter_match_options_alter_tournament_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['round__index', 'slot']},
        ),
        migrations.AlterModelOptions(
            name='tournament',
            options={},
        ),
        migrations.RemoveField(
            model_name='teammembership',
            name='joined_at',
        ),
        migrations.AddField(
            model_name='team',
            name='max_players',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='tournament',
            name='default_team_size',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='team',
            name='participant1',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='team',
            name='participant2',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(related_name='teams', through='mavtournaments.TeamMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teammembership',
            name='role',
            field=models.CharField(default='player', max_length=20),
        ),
        migrations.AlterField(
            model_name='teammembership',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='mavtournaments.team'),
        ),
    ]
